[package]
name = "rust-ffi-demo"
version = "0.1.0"
edition = "2024"
build = "build.rs"



[dependencies]
libc = "0.2.0"


[lib]
# The available options are bin, lib, rlib, dylib, cdylib, staticlib, and proc-macro. 
# You can read more about the different crate types in the Rust Reference Manual.
crate-type = ["cdylib"]


[build-dependencies]
cc = "1.4.2" # c compiler 调用c编译器，将c代码编译为静态库